[package]
name = "cryptopals_rust"
version = "0.1.0"
authors = ["Brendon Walsh <brendonwalsh@niamu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
